# Generated by Django 5.1.2 on 2024-11-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_prod', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('sabor', models.CharField(max_length=15)),
                ('precio', models.FloatField()),
                ('peso', models.FloatField()),
                ('id_proveedor', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
