# Generated by Django 5.1.2 on 2024-11-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_provee', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('id_empleado', models.IntegerField()),
                ('num_vehiculo', models.CharField(max_length=10)),
                ('id_producto', models.IntegerField()),
                ('id_sucursal', models.IntegerField()),
            ],
        ),
    ]
