# Generated by Django 5.1 on 2024-11-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=50)),
                ('rfc', models.CharField(max_length=15)),
                ('curp', models.CharField(max_length=18)),
                ('num_tel', models.CharField(max_length=10)),
                ('dire', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_empleado/')),
            ],
        ),
    ]
