# Generated by Django 5.1.2 on 2024-11-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=50)),
                ('num_tel', models.CharField(max_length=12)),
                ('dire', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=25)),
            ],
        ),
    ]
